name: Deploy to Tencent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install coscmd
        run: pip install coscmd

      - name: Deploy to COS
        run: |
          coscmd config -a ${{ secrets.TCB_SECRET_ID }} -s ${{ secrets.TCB_SECRET_KEY }} -b degen-1256918364 -r ap-hongkong
          coscmd upload -H '{"Content-Type":"text/html; charset=utf-8"}' index.html /index.html
          coscmd upload -H '{"Content-Type":"text/html; charset=utf-8"}' help.html /help.html
